version: "3.3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    links:
      - fpm
    networks:
      - app-network

  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    links:
      - mysql  
    volumes:
      - ./:/var/www
    networks:
      - app-network

  mysql:
      image: mysql:5.7
      ports:
        - 33061:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
      networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge